# Generated by Django 4.1.10 on 2023-08-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='region',
            new_name='region_id',
        ),
    ]
