# Generated by Django 4.1.10 on 2023-08-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_region_district_region_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='region_id',
            new_name='region',
        ),
    ]
